import template from 'lodash/template';
import { repairPath } from '../../utils/fileUtils';
import { path } from '../../utils/electronUtils';
import { checkFileExists } from '../utils';
import { format } from '../../export/utils';

const templateContent = `
import React from 'react';
import PropTypes from 'prop-types';

const rootStyle: any = {
    padding: '2em',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
};

/*
  <%= componentName %> component generated by Webcodesk 
 */
class <%= componentName %> extends React.Component<<%= componentName %>Props, any> {
  static propTypes = {
    // any arbitrary data
    data: PropTypes.object,
    // send the data by click
    onClick: PropTypes.func,
  };

  static defaultProps = {
    data: {},
    onClick: () => {
      // is not set
    },
  };  
  
  constructor (props: <%= componentName %>Props) {
    super(props);
  }

  handleClick = (e: any) => {
    if (e) {
      e.stopPropagation();
      e.preventDefault();
    }
    const { onClick, data } = this.props;
    onClick(data);
  };

  render () {
    const { data } = this.props;
    return (
      <div style={rootStyle}>
        <button onClick={this.handleClick}>Click</button>
      </div>
    );
  }
}

export default <%= componentName %>;
`;

const templateContentD_TS = `
interface <%= componentName %>Props {
  data: any;
  onClick: (data: any) => void;
}
`;

export async function createFiles (componentName, dirName, destDirPath, fileExtension) {
  const fileObjects = [];
  let fileExists;
  const componentFilePath = repairPath(path().join(destDirPath, dirName, `${componentName}${fileExtension}`));
  fileExists = await checkFileExists(componentFilePath);
  if (fileExists) {
    throw Error(`The file with the "${componentName}${fileExtension}" name already exists.`);
  }
  const typesFilePath = repairPath(path().join(destDirPath, dirName, `i${componentName}.d.ts`));
  fileExists = await checkFileExists(typesFilePath);
  if (fileExists) {
    throw Error(`The file with the "i${componentName}.d.ts" name already exists.`);
  }
  fileObjects.push({
    filePath: componentFilePath,
    fileData: format(template(templateContent)({
      componentName
    }))
  });
  fileObjects.push({
    filePath: typesFilePath,
    fileData: template(templateContentD_TS)({
      componentName
    })
  });
  return fileObjects;
}